---
version: "3"

env:
  APPLICATION_NAME: brr
  DEBUG: false

tasks:
  default:
    silent: true
    cmds:
      - task -l

  install:
    desc: install app
    cmds:
      - cp ${APPLICATION_NAME} /usr/local/bin/${APPLICATION_NAME}

  build:
    desc: build app
    cmds:
      - go mod tidy
      - go build -ldflags '-s -w' -o ./${APPLICATION_NAME}

  lint:
    desc: run linter
    cmds:
      - golangci-lint run .

  fmt:
    desc: run formatter
    cmds:
      - go fmt .

  upgrade-deps:
    desc: upgrade all dependencies
    cmds:
      - go get -u ./...

  vet:
    desc: run go vet
    cmds:
      - go vet

  vuln:
    desc: check for vulnerabilities
    cmds:
      - govulncheck .
